/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyThirdwebComponent {
    }
}
declare global {
    interface HTMLMyThirdwebComponentElement extends Components.MyThirdwebComponent, HTMLStencilElement {
    }
    var HTMLMyThirdwebComponentElement: {
        prototype: HTMLMyThirdwebComponentElement;
        new (): HTMLMyThirdwebComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-thirdweb-component": HTMLMyThirdwebComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyThirdwebComponent {
    }
    interface IntrinsicElements {
        "my-thirdweb-component": MyThirdwebComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-thirdweb-component": LocalJSX.MyThirdwebComponent & JSXBase.HTMLAttributes<HTMLMyThirdwebComponentElement>;
        }
    }
}
